TrajectoryPlannerROS:
  max_vel_x: 0.25
  min_vel_x: -0.25
  max_vel_theta: 1.85
  min_vel_theta: -1.85
  min_in_place_vel_theta: -1.85
  max_in_place_vel_theta: -1.85
  acc_lim_theta: 10
  acc_lim_x: 0.5
  meter_scoring: true
  

  holonomic_robot: false
  yaw_goal_tolerance: 1  # about 6 degrees
  xy_goal_tolerance: 0.2  # 20 cm
  latch_xy_goal_tolerance: false
  cost_scaling_factor: 1.0

  transform_tolerance: 10
  controller_frequency: 10

  sim_time: 3.0
  