controller_frequency: 5.0
TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.05
  max_vel_theta: 0.8
  min_vel_theta: 0.08
  min_in_place_vel_theta: 0.1
  acc_lim_theta: 2
  acc_lim_x: 0.5
  meter_scoring: true

  holonomic_robot: false
  yaw_goal_tolerance: 1  # about 6 degrees
  xy_goal_tolerance: 0.05  # 20 cm
  latch_xy_goal_tolerance: false
  cost_scaling_factor: 1.5

  transform_tolerance: 10
  controller_frequency: 5.0
  sim_time: 2.0 
  occ_dist_scale: 0.01
  pdist_scale: 11
  gdist_scale: 0.8

  escape_vel: -0.1
