obstacle_range: 1 # This was 2.5
raytrace_range: 3.0
robot_radius: 0.1
inflation_radius: 0.01  # Def was 0.5
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: lidar_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}